export const suggestions = [
    "Is Kamala Harris Black?",
    "Was the 2020 U.S. presidential election stolen?",
    "Is climate change a hoax?",
    "Do vaccines cause autism?",
    "Do COVID-19 vaccines contain microchips?",
    "Does 5G technology spread COVID-19?",
    "Is the Earth flat?",
    "Was the moon landing faked?",
    "Is Barack Obama not a U.S. citizen?",
    "Does George Soros fund Antifa?",
    "Do flu vaccines give you the flu?",
    "Did Donald Trump win the popular vote in 2020?",
    "Do wind turbines cause cancer?",
    "Did Bill Gates create COVID-19 for profit?",
    "Does drinking bleach cure COVID-19?",
    "Did the Holocaust happen?",
    "Did the FBI assassinate Martin Luther King Jr.?",
    "Did Hillary Clinton run a child trafficking ring from a pizza shop?",
    "Is the Great Wall of China visible from space?",
    "Was COVID-19 created in a lab as a bioweapon?",
    "Does eating carrots improve your eyesight?",
    "Does marijuana cure cancer?",
    "Do vaccines cause infertility?",
    "Is Antarctica a military no-go zone for secret experiments?",
    "Are masks ineffective at preventing COVID-19 spread?",
    "Is global warming caused by solar cycles, not humans?",
    "Is Elvis Presley still alive?",
    "Did the Titanic sink, or was it another ship?",
    "Is Prince Charles a vampire?",
    "Does eating chocolate cause acne?",
    "Was Jeffrey Epstein murdered?",
    "Did dinosaurs and humans coexist?",
    "Was COVID-19 a planned pandemic ('Plandemic')?",
    "Does smoking not cause lung cancer?",
    "Do Native Americans have no legal rights in the U.S.?",
    "Do humans only use 10% of their brains?",
    "Is Queen Elizabeth II a reptilian alien?",
    "Do you need to drink eight glasses of water a day?",
    "Does Joe Biden have dementia?",
    "Is the 5-second rule for dropped food real?",
    "Is evolution just a theory?",
    "Is the vaccine passport the mark of the beast?",
    "Are chemtrails government experiments on humans?",
    "Is Pluto not a planet?",
    "Was O.J. Simpson innocent?",
    "Does the Bermuda Triangle cause disappearances due to supernatural forces?",
    "Is the Loch Ness monster real?",
    "Did Donald Trump avoid taxes by exploiting loopholes?",
    "Does Bigfoot exist?",
    "Did ancient aliens build the pyramids?",
    "Does fluoride in water lower IQ?",
    "Can vaccinated people shed COVID-19 and infect others?",
    "Does wearing a bra cause breast cancer?",
    "Were the pyramids power plants?",
    "Do sharks not get cancer?",
    "Does the CIA control the media?",
    "Does the Illuminati control the world?",
    "Is eating GMOs dangerous for health?",
    "Did Adolf Hitler survive World War II?",
    "Do black holes lead to alternate dimensions?",
    "Is the government hiding evidence of UFOs?",
    "Did the U.S. fake Pearl Harbor to join World War II?",
    "Is climate change a naturally occurring cycle?",
    "Does the moon control human behavior?",
    "Did Paul McCartney die in 1966 and get replaced by a lookalike?",
    "Is gluten intolerance a myth?",
    "Do vaccines contain dangerous toxins like mercury?",
    "Is the Federal Reserve privately owned and not accountable?",
    "Does free energy technology exist but is being suppressed?",
    "Does burning sage cleanse a house of spirits?",
    "Did ancient Rome not exist?",
    "Is the World Health Organization part of a global depopulation plan?",
    "Does eating too much sugar cause diabetes?",
    "Did Nikola Tesla invent a death ray?",
    "Are birds government drones?",
    "Can water cure cancer?",
    "Does the Catholic Church hold secret alien artifacts?",
    "Was Bitcoin created by the CIA?",
    "Do the pyramids align with Orion's belt?",
    "Is the New World Order planning global domination?",
    "Does the Pope secretly control world governments?",
    "Do Wi-Fi signals cause brain cancer?",
    "Did the COVID-19 pandemic come from 5G?",
    "Does caffeine stunt growth?",
    "Is the IRS not a legitimate organization?",
    "Do lizard people control the government?",
    "Does the FDA approve harmful drugs for profit?",
    "Does Listerine kill COVID-19?",
    "Was JFK's assassination a government plot?",
    "Does microwaving food make it lose nutritional value?",
    "Did George W. Bush know about 9/11 beforehand?",
    "Does Bill Gates want to depopulate the world?",
    "Does aluminum in deodorants cause breast cancer?",
    "Does the Rothschild family control all the world's banks?",
    "Did aliens build Stonehenge?",
    "Can the government control the weather using HAARP?",
    "Does adding salt to water make it boil faster?",
    "Do fish only have a 3-second memory?",
    "Can vaccines alter your DNA?",
    "Will Jeffrey Epstein's clients never be revealed?"
];

export const mockData = [
    "Is Kamala Harris Black?",
    "Was the 2020 U.S. presidential election stolen?",
    "Is climate change a hoax?",
    "Do vaccines cause autism?",
    "Do COVID-19 vaccines contain microchips?",
    "Does 5G technology spread COVID-19?",
    "Is the Earth flat?",
    "Was the moon landing faked?",
    "Is Barack Obama not a U.S. citizen?",
    "Does George Soros fund Antifa?",
    "Do flu vaccines give you the flu?",
    "Did Donald Trump win the popular vote in 2020?",
    "Do wind turbines cause cancer?",
    "Did Bill Gates create COVID-19 for profit?",
    "Does drinking bleach cure COVID-19?",
    "Did the Holocaust happen?",
    "Did the FBI assassinate Martin Luther King Jr.?",
    "Did Hillary Clinton run a child trafficking ring from a pizza shop?",
    "Is the Great Wall of China visible from space?",
    "Was COVID-19 created in a lab as a bioweapon?",
    "Does eating carrots improve your eyesight?",
    "Does marijuana cure cancer?",
    "Do vaccines cause infertility?",
    "Is Antarctica a military no-go zone for secret experiments?",
    "Are masks ineffective at preventing COVID-19 spread?",
    "Is global warming caused by solar cycles, not humans?",
    "Is Elvis Presley still alive?",
    "Did the Titanic sink, or was it another ship?",
    "Is Prince Charles a vampire?",
    "Does eating chocolate cause acne?",
    "Was Jeffrey Epstein murdered?",
    "Did dinosaurs and humans coexist?",
    "Was COVID-19 a planned pandemic ('Plandemic')?",
    "Does smoking not cause lung cancer?",
    "Do Native Americans have no legal rights in the U.S.?",
    "Do humans only use 10% of their brains?",
    "Is Queen Elizabeth II a reptilian alien?",
    "Do you need to drink eight glasses of water a day?",
    "Does Joe Biden have dementia?",
    "Is the 5-second rule for dropped food real?",
    "Is evolution just a theory?",
    "Is the vaccine passport the mark of the beast?",
    "Are chemtrails government experiments on humans?",
    "Is Pluto not a planet?",
    "Was O.J. Simpson innocent?",
    "Does the Bermuda Triangle cause disappearances due to supernatural forces?",
    "Is the Loch Ness monster real?",
    "Did Donald Trump avoid taxes by exploiting loopholes?",
    "Does Bigfoot exist?",
    "Did ancient aliens build the pyramids?",
    "Does fluoride in water lower IQ?",
    "Can vaccinated people shed COVID-19 and infect others?",
    "Does wearing a bra cause breast cancer?",
    "Were the pyramids power plants?",
    "Do sharks not get cancer?",
    "Does the CIA control the media?",
    "Does the Illuminati control the world?",
    "Is eating GMOs dangerous for health?",
    "Did Adolf Hitler survive World War II?",
    "Do black holes lead to alternate dimensions?",
    "Is the government hiding evidence of UFOs?",
    "Did the U.S. fake Pearl Harbor to join World War II?",
    "Is climate change a naturally occurring cycle?",
    "Does the moon control human behavior?",
    "Did Paul McCartney die in 1966 and get replaced by a lookalike?",
    "Is gluten intolerance a myth?",
    "Do vaccines contain dangerous toxins like mercury?",
    "Is the Federal Reserve privately owned and not accountable?",
    "Does free energy technology exist but is being suppressed?",
    "Does burning sage cleanse a house of spirits?",
    "Did ancient Rome not exist?",
    "Is the World Health Organization part of a global depopulation plan?",
    "Does eating too much sugar cause diabetes?",
    "Did Nikola Tesla invent a death ray?",
    "Are birds government drones?",
    "Can water cure cancer?",
    "Does the Catholic Church hold secret alien artifacts?",
    "Was Bitcoin created by the CIA?",
    "Do the pyramids align with Orion's belt?",
    "Is the New World Order planning global domination?",
    "Does the Pope secretly control world governments?",
    "Do Wi-Fi signals cause brain cancer?",
    "Did the COVID-19 pandemic come from 5G?",
    "Does caffeine stunt growth?",
    "Is the IRS not a legitimate organization?",
    "Do lizard people control the government?",
    "Does the FDA approve harmful drugs for profit?",
    "Does Listerine kill COVID-19?",
    "Was JFK's assassination a government plot?",
    "Does microwaving food make it lose nutritional value?",
    "Did George W. Bush know about 9/11 beforehand?",
    "Does Bill Gates want to depopulate the world?",
    "Does aluminum in deodorants cause breast cancer?",
    "Does the Rothschild family control all the world's banks?",
    "Did aliens build Stonehenge?",
    "Can the government control the weather using HAARP?",
    "Does adding salt to water make it boil faster?",
    "Do fish only have a 3-second memory?",
    "Can vaccines alter your DNA?",
    "Will Jeffrey Epstein's clients never be revealed?"
];
